comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch: off
    # patch:
    #   default:
    #     target: auto
    #     threshold: 1%
    #     informational: true

fixes:
  - "::hyperSpec/"
