# Note: This script automatically detects the repository in which it is run.
# No edits are needed except in the "Install Dependencies" section where
# one may need to install additional packages according to the needs.


on:
  push:
    branches:
      - develop

# Note on the above: if more than one branch given one may stomp on the other
# during deployment, so use only one branch.
name: R-CMD-build-check-deploy

jobs:
  R-CMD-build-check-deploy:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: ubuntu-16.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      REPO: ${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps("./hyperSpec", dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('./hyperSpec/DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          remotes::install_deps("./hyperSpec", dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("roxygen2")
          remotes::install_cran("drat") # need later to deploy
        shell: Rscript {0}

      - name: Roxygenize
        run: |
          devtools::document("./hyperSpec", roclets = c('rd', 'collate', 'namespace'))
          devtools::document("./hyperSpec", roclets = c('vignette'))
        shell: Rscript {0}

      - name: Build and Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: |
          rcmdcheck::rcmdcheck(
            "./hyperSpec",
            args = c("--no-manual", "--as-cran"),
            error_on = "warning",
            check_dir = "hyperSpec/check"
          )
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

# Everything above is standard build & check steps
# Now the steps to deploy to hySpc.pkgs

# Very Important Note: Each "- name:" task below starts from the same
# directory, which in this case is
# /home/runner/work/hySpc.read.txt/hySpc.read.txt
# Each task is run in its own shell starting from this directory.
# This means you have to navigate to the desired directory for each task.

# The following configure step is
# from https://stackoverflow.com/a/60548651/633251
      - name: Configure git
        env:
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

          # CUST update the name of the local repo "bot"
          git config --global user.email "${REPO}_Deploy_Bot@example.com"
          git config --global user.name "${REPO} Deploy Bot"

      - name: Deploy -- clone
        if: success()
        run: |
          pwd
          cd hyperSpec
          rm -rf hySpc.pkgs
          git clone https://github.com/r-hyperspec/hySpc.pkgs.git hySpc.pkgs
          cd hySpc.pkgs
          git checkout gh-pages

      - name: Deploy -- insert
        if: success()
        run: |
          targz <- list.files(
            path = "hyperSpec/check",
            pattern = "\\.tar\\.gz",
            full.names = TRUE
          )[1] # there will be only one in this directory!

          drat::insertPackage(
            targz,
            repodir = "hyperSpec/hySpc.pkgs",
            action = "archive"
          )
        shell: Rscript {0}

      - name: Deploy -- update README.md
        if: success()
        run: |
           cd hyperSpec/hySpc.pkgs
           # grab the portion of the file we want to re-use
           awk '/^# hySpc\.pkgs$/, /^Packages currently residing here:$/' README.md > README.tmp
           # append the listing of .tar.gz present, along with a little md formating
           ls -lhR  --time-style=long-iso | grep \.tar\.gz$ | awk '{print "\n* "$8, " ("$6")"}' >> README.tmp
           mv README.tmp README.md

      - name: Deploy -- commit and push
        if: success()
        run: |
          cd hyperSpec/hySpc.pkgs
          git add *
          # .tar.gz files are globally blocked by git, must add manually
          # and force it
          # git add -f *.tar.gz
          git commit -m "Automated deploy from ${REPO}" #CUST
          git push origin gh-pages
